export default {
  START_INSURANCE_LOADING: "START_INSURANCE_LOADING",
  LOAD_BRANDS: "LOAD_BRANDS",
  LOAD_MODELS: "LOAD_MODELS",
  LOAD_VARIANTS: "LOAD_VARIANTS",
  LOAD_QUOTATION_PLANS: "LOAD_QUOTATION_PLANS",
  LOAD_CART_DETAILS: "LOAD_CART_DETAILS"
};
