export default {
  START_INSURANCE_LOADING: "START_INSURANCE_LOADING",
  LOAD_BRANDS: "LOAD_BRANDS",
  LOAD_MODELS: "LOAD_MODELS",
  LOAD_VARIANTS: "LOAD_VARIANTS",
  LOAD_REGISTRATION_CODES: "LOAD_REGISTRATION_CODES",
  LOAD_QUOTATION_PLANS: "LOAD_QUOTATION_PLANS",
  LOAD_CART_DETAILS: "LOAD_CART_DETAILS",
  LOAD_VEHICLE_OWNER: "LOAD_VEHICLE_OWNER",
  LOAD_ADDRESS: "LOAD_ADDRESS",
  LOAD_VEHICLE_DETAIL: "LOAD_VEHICLE_DETAIL",
  LOAD_PAST_POLICY: "LOAD_PAST_POLICY",
  LOAD_COMPANIES: "LOAD_COMPANIES"
};
