export default {
  LOAD_TENANT: "LOAD_TENANT",
  LOAD_ROLES: "LOAD_ROLES",
  LOAD_ROLE_LIST: "LOAD_ROLE_LIST",
  LOAD_USERS: "LOAD_USERS",
  LOAD_USER_LIST: "LOAD_USER_LIST",
  LOADING_TENANT: "LOADING_TENANT",
  LOAD_PRIVILEGES_LIST: "LOAD_PRIVILEGES_LIST"
};
