export default {
  START_TENANT_LOADING: "START_TENANT_LOADING",
  STOP_TENANT_LOADING: "STOP_TENANT_LOADING",
  LOAD_ROLE: "LOAD_ROLE",
  LOAD_ROLES: "LOAD_ROLES",
  LOAD_ROLE_LIST: "LOAD_ROLE_LIST",
  LOAD_USERS: "LOAD_USERS",
  LOAD_USER_LIST: "LOAD_USER_LIST",
  LOAD_PRIVILEGES: "LOAD_PRIVILEGES"
};
