export default {
  START_LOADING: "START_LOADING",
  STOP_LOADING: "STOP_LOADING",
  LOAD_ROLES: "LOAD_ROLES",
  LOAD_ROLE_LIST: "LOAD_ROLE_LIST",
  LOAD_USERS: "LOAD_USERS",
  LOAD_USER_LIST: "LOAD_USER_LIST",
  LOAD_PRIVILEGES_LIST: "LOAD_PRIVILEGES_LIST"
};
