export default {
  START_USER_LOADING: "START_USER_LOADING",
  STOP_USER_LOADING: "STOP_USER_LOADING",
  LOAD_AUTH: "LOAD_AUTH",
  LOG_OUT: "LOG_OUT",
  LOAD_USER_PRIVILEGES: "LOAD_USER_PRIVILEGES",
  LOAD_USER: "LOAD_USER",
  SET_ROUTE_VALIDITY: "SET_ROUTE_VALIDITY"
};
