export default {
  START_USER_LOADING: "START_USER_LOADING",
  STOP_USER_LOADING: "STOP_USER_LOADING",
  LOAD_AUTH: "LOAD_AUTH",
  LOAD_USER_PRIVILEGES: "LOAD_USER_PRIVILEGES",
  LOAD_USER: "LOAD_USER",
  LOAD_USER_DETAILS: "LOAD_USER_DETAILS"
};
